# Generated by Django 4.1.6 on 2023-02-16 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
