# Generated by Django 4.1.6 on 2023-02-13 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_postimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
